version: '3.10'

services:
  apiserver:
    image: nvcr.io/nvidia/pytorch:23.08-py3
    command: bash run.sh
    ulimits:
      stack: 67108864
      memlock: -1
    volumes:
      - $PWD:/workspace
      - /root/model/:/workspace/checkpoints/
    env_file:
      - .env
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]